export const roomData = [
    {
      id: 1,
      name: "Deluxe Room",
      description: "A spacious room with a view of the city.",
      price: 1224,
      image: require("../../../Page/Rooms/RoomImages/Bedroom1.jpg"),
      amenities: ['Free Wi-Fi', 'Air Conditioning', 'Mini-bar', 'Private Bathroom', 'TV'],
    },
    {
      id: 2,
      name: "Twin Room",
      description: "A spacious room with a view of the city.",
      price: 1143,
      image: require("../../../Page/Rooms/RoomImages/bedroom7.jpg"),
      amenities: ['Free Wi-Fi', 'Air Conditioning', 'Private Bathroom', 'TV'],
    },
    {
      id: 3,
      name: "Haddasah Suite",
      description: "A spacious room with a view of the city.",
      price: 1251,
      image: require("../../../Page/Rooms/RoomImages/Bedroom3.jpg"),
      amenities: ['Free Wi-Fi', 'Air Conditioning', 'Mini-bar', 'Private Bathroom', 'TV'],
    },
    {
      id: 4,
      name: "Blair Suite",
      description: "A spacious room with a view of the city.",
      price: 1390,
      image: require("../../../Page/Rooms/RoomImages/bedroom4.jpg"),
      amenities: ['Free Wi-Fi', 'Air Conditioning', 'Mini-bar', 'Private Bathroom', 'TV'],
    },
    {
      id: 5,
      name: "Zapphora Suite",
      description: "A spacious room with a view of the city.",
      price: 3420,
      image: require("../../../Page/Rooms/RoomImages/bedroom5.jpg"),
      amenities: ['Free Wi-Fi', 'Air Conditioning', 'Mini-bar', 'Private Bathroom', 'TV', 'Private Garden'],
    },
    {
      id: 6,
      name: "Manroe Suite",
      description: "A spacious room with a view of the city.",
      price: 3800,
      image: require("../../../Page/Rooms/RoomImages/Bedroom6.jpg"),
      amenities: ['Free Wi-Fi', 'Air Conditioning', 'Mini-bar', 'Private Bathroom', 'Private Pool', 'TV'],
    },
  ];